project:
  type: website
  output-dir: docs

website:
  open-graph: TRUE
  title: "The Linear Mixed Modelers"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - literature.qmd
      - report.qmd
      - about.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

